#use_frameworks!
#
#platform :ios, '10.0'

target 'IPDSDK_Example' do
  pod 'IPDSDK'#, :path => '../'
#  pod 'IPDSDK/IPDSDKModuleGoogle', :path => '../'
  target 'IPDSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
